name: 'chromatic should deploy'
description: 'Checks if storybook build changed from previous commit  '
author: 'fddayan'
branding:
  icon: 'alert-triangle'  
  color: 'green'
inputs:
  githubUser:
    required: true
    description: The github user to be used to pull the artifact
  artifactName:
    required: true  
    description: "The artifact name to store"
  previousSha:
    required: false
    description: "Previous sha commit to checkout to build storybook in case artifact is not present."
    default: ${{github.event.before}}
outputs:
  shouldDeploy:
    description: TRUE/FALSE value if it should deploy chromatic based on previous build
    value: ${{ steps.chromatic-checker.outputs.shouldDeploy }}

runs:
  using: 'composite'
  steps:
    - uses: bluwy/substitute-string-action@v1
      id: sub
      with:
        _input-text: '${{inputs.artifactName}}'
        /: '-'
    - name: Artifact exists
      id: 'previous_artifact'
      uses: fddayan/archive-exists@v1.1.0
      with:        
        # artifactName: storybook-hash-file-${{ steps.sub.outputs.result }}
        artifactName: ${{ steps.sub.outputs.result }}
    - name: Artifact download 
      if: ${{steps.previous_artifact.outputs.artifactsFound == 'TRUE'}}
      run: |
        curl -L -u ${{ inputs.githubUser }}:${{ github.token }} -o storybook-hash-previous.txt.zip -H "Accept: application/vnd.github.v3+json" ${{steps.previous_artifact.outputs.artifactDownloadUrl}}
      shell: bash
    - name: Unzip Artifact
      if: ${{steps.previous_artifact.outputs.artifactsFound == 'TRUE'}}
      run: |
          unzip storybook-hash-previous.txt.zip
          mv storybook-hash-current.txt storybook-hash-previous.txt
          cat storybook-hash-previous.txt
      shell: bash
    - uses: actions/checkout@v2
      if: ${{steps.previous_artifact.outputs.artifactsFound == 'FALSE'}}
      with:
        fetch-depth: 0
        path: previous
        ref: ${{inputs.previousSha}}
    - name: Build Storybook in previous build
      if: ${{steps.previous_artifact.outputs.artifactsFound == 'FALSE'}}
      run: npm run build-storybook > /dev/null 2>&1
      working-directory: previous
      shell: bash
    - name: Build Storybook in current build
      run: npm run build-storybook > /dev/null 2>&1
      shell: bash
    - name: Generate hash for previous commit from current storybook build
      if: ${{steps.previous_artifact.outputs.artifactsFound == 'FALSE'}}
      run: | 
        find ./previous/storybook-static/ -type f -exec md5sum {} \; | md5sum > storybook-hash-previous.txt
        cat storybook-hash-previous.txt
      shell: bash
    - name: Get hash values for previous and current storybook builds
      id: storybook-hash
      run: |          
         find ./storybook-static/ -type f -exec md5sum {} \; | md5sum > storybook-hash-current.txt
         cat storybook-hash-current.txt
         echo "::set-output name=previous_hash::$(cat storybook-hash-previous.txt)"
         echo "::set-output name=current_hash::$(cat storybook-hash-current.txt)"
      shell: bash
    - name: Archive current Storybook build hash
      uses: actions/upload-artifact@v2
      with:
        # name: storybook-hash-file-${{ steps.sub.outputs.result }}
        name: ${{ steps.sub.outputs.result }}
        path: storybook-hash-current.txt
    - name: Print info
      run: |
        echo "Previous hash: ${{ steps.storybook-hash.outputs.previous_hash}}"
        echo "Current hash: ${{steps.storybook-hash.outputs.current_hash }}"
        echo "Should deploy: ${{ steps.storybook-hash.outputs.previous_hash != steps.storybook-hash.outputs.current_hash }}"
        echo "Artifact found: ${{steps.previous_artifact.outputs.artifactsFound}}"
      shell: bash
    - run: echo "::set-output name=shouldDeploy::${{ steps.storybook-hash.outputs.previous_hash != steps.storybook-hash.outputs.current_hash }}"
      id: chromatic-checker
      shell: bash
