name: 'chromatic should deploy'
description: 'Checks if storybook build changed from previous commit  '
author: 'fddayan'
branding:
  icon: 'alert-triangle'  
  color: 'green'
outputs:
  should_deploy:
    description: TRUE/FALSE value if it should deploy chromatic based on previous build
    value: ${{ steps.chromatic-checker.outputs.should_deploy }}

# runs:
#   using: 'node12'
#   main: 'dist/index.js'
runs:
  using: 'composite'
  steps:
    - uses: bluwy/substitute-string-action@v1
      id: sub
      with:
        _input-text: '${{ github.head_ref }}'
        /: '-'
    - name: Get sha values
      id: git_sha
      shell: bash
      run: |
        echo "::set-output name=current_sha_short::$(git rev-parse HEAD)"
        echo "::set-output name=previous_sha_short::$(git rev-parse HEAD~1)"
    - name: Archive exists
      id: 'previous_archive'
      uses: fddayan/archive-exists@main
      with:        
        artifactName: storybook-hash-file-${{ steps.sub.outputs.result }}
        download: true
        downloadTo: storybook-hash-previous.txt
    - name: Archive download 
      run: |
        curl -L -u taskrabbit:${{ github.token }} -o storybook-hash-previous.txt.zip -H "Accept: application/vnd.github.v3+json" ${{steps.previous_archive.outputs.artifactDownloadUrl}}
      shell: bash
    - run: |
          ls
          echo "---------------"
          cat storybook-hash-previous.txt.zip
          unzip storybook-hash-previous.txt.zip
          echo "---------------"
          cat storybook-hash-previous.txt.zip
      shell: bash
    - uses: actions/checkout@v2
      if: ${{steps.previous_archive.outputs.artifacts_found == 'FALSE'}}
      with:
        fetch-depth: 0
        path: previous
        ref: ${{ github.event.before }}
    - name: Build Storybook in previous build
      if: ${{steps.previous_archive.outputs.artifacts_found == 'FALSE'}}
      run: npm run build-storybook > /dev/null 2>&1
      working-directory: previous
      shell: bash
    - name: Build Storybook in current build
      run: npm run build-storybook > /dev/null 2>&1
      shell: bash
    - name: Generate hash for previous commit from current storybook build
      if: ${{steps.previous_archive.outputs.artifacts_found == 'FALSE'}}
      run: | 
        find ./previous/storybook-static/ -type f -exec md5sum {} \; | md5sum > storybook-hash-previous.txt
        cat storybook-hash-previous.txt
      shell: bash
    - name: Get hash values for previous and current storybook builds
      id: storybook-hash
      run: |          
         find ./storybook-static/ -type f -exec md5sum {} \; | md5sum > storybook-hash-current.txt
         cat storybook-hash-current.txt
         echo "::set-output name=previous_hash::$(cat storybook-hash-previous.txt)"
         echo "::set-output name=current_hash::$(cat storybook-hash-current.txt)"
      shell: bash
    - name: Archive current Storybook build hash
      uses: actions/upload-artifact@v2
      with:
        name: storybook-hash-file-${{ steps.sub.outputs.result }}
        path: storybook-hash-current.txt
    - name: Print info
      run: |
        echo "Previous hash: ${{ steps.storybook-hash.outputs.previous_hash}}"
        echo "Current hash: ${{steps.storybook-hash.outputs.current_hash }}"
        echo "Should deploy: ${{ steps.storybook-hash.outputs.previous_hash != steps.storybook-hash.outputs.current_hash }}"
        echo "Artifact found: ${{steps.previous_archive.outputs.artifacts_found}}"
      shell: bash
    - run: echo "::set-output name=should_deploy::${{ steps.storybook-hash.outputs.previous_hash != steps.storybook-hash.outputs.current_hash }}"
      id: chromatic-checker
      shell: bash
