name: 'chromatic should deploy'
description: 'Checks if storybook build changed from previous commit  '
author: 'fddayan'
branding:
  icon: 'alert-triangle'  
  color: 'green'
inputs:
  githubUser:
    required: true
    description: The github user to be used to pull the artifact
  artifactName:
    required: true  
    description: "The artifact name to store"
  previousSha:
    required: false
    description: "Previous sha commit to checkout to build storybook in case artifact is not present."
    default: ${{github.event.before}}
  GITHUB_TOKEN:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to create or update the comment. This defaults to {{ github.token }}.'
    default: '${{ github.token }}'
    required: false
  storybookBuildCommand:
    description: Command to run to build storybook.
    required: false
    default: npm run build-storybook
  debug:
    description: 'if set to true it will upload the output of storybook build as artifacts.'
    default: false
    required: false
outputs:
  shouldDeploy:
    description: TRUE/FALSE value if it should deploy chromatic based on previous build
    value: ${{ steps.chromatic-checker.outputs.shouldDeploy }}

runs:
  using: 'composite'
  steps:    
    # - uses: bluwy/substitute-string-action@v1
    #   id: sub
    #   with:
    #     _input-text: '${{inputs.artifactName}}'
    #     /: '-'
    # - name: Artifact exists
    #   id: 'previous_artifact'
    #   uses: fddayan/archive-exists@v1.1.0
    #   with:        
    #     artifactName: ${{inputs.artifactName}}
    # - name: Artifact download 
    #   if: ${{steps.previous_artifact.outputs.artifactsFound == 'TRUE'}}
    #   run: |
    #     curl -L -u ${{ inputs.githubUser }}:${{ github.token }} -o storybook-hash-previous.txt.zip -H "Accept: application/vnd.github.v3+json" ${{steps.previous_artifact.outputs.artifactDownloadUrl}}
    #   shell: bash
    # - name: Unzip Artifact
    #   if: ${{steps.previous_artifact.outputs.artifactsFound == 'TRUE'}}
    #   run: |
    #       unzip storybook-hash-previous.txt.zip
    #       mv storybook-hash-current.txt storybook-hash-previous.txt
    #       cat storybook-hash-previous.txt
    #   shell: bash
    - name: Download artifact with previous storybook build hash
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{inputs.GITHUB_TOKEN}}
        workflow: main_pulls.yml
        branch: ${{ github.event.pull_request.head.ref }}
        name: ${{inputs.artifactName}}
        path: storybook-hash
        check_artifacts: false    
    - name: Checks previous artifact existence
      id: previous_artifact
      uses: andstor/file-existence-action@v1.1.0
      with:
        files: "storybook-hash/storybook-hash-current.txt"
    - name: Unzip Artifact
      if: ${{steps.previous_artifact.outputs.files_exists == 'true'}}
      run: |
        mv storybook-hash/storybook-hash-current.txt ./storybook-hash-previous.txt
      shell: bash
    - uses: actions/checkout@v2
      if: ${{steps.previous_artifact.outputs.files_exists == 'false'}}
      with:
        fetch-depth: 0
        path: previous
        ref: ${{inputs.previousSha}}
    - name: Build Storybook in previous build
      if: ${{steps.previous_artifact.outputs.files_exists == 'false'}}
      run: ${{inputs.storybookBuildCommand}} > build-storybook-previous.log 2>&1
      working-directory: previous
      shell: bash
    - name: Build Storybook in current build
      run: ${{inputs.storybookBuildCommand}} > build-storybook-current.log 2>&1
      shell: bash
    - name: Upload previous storybook build output
      if: ${{inputs.debug == 'true' && steps.previous_artifact.outputs.files_exists == 'false'}}
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.artifactName}}-storybook-build-previous
        path: build-storybook-previous.log
    - name: Upload current storybook build output
      if: ${{inputs.debug == 'true'}}
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.artifactName}}-storybook-build-current
        path: build-storybook-current.log
    - name: Generate hash for previous commit from current storybook build
      if: ${{steps.previous_artifact.outputs.files_exists == 'false'}}
      run: | 
        find ./previous/storybook-static/ -type f -exec md5sum {} \; | md5sum > storybook-hash-previous.txt
        cat storybook-hash-previous.txt
      shell: bash
    - name: Get hash values for previous and current storybook builds
      id: storybook-hash
      run: |          
         find ./storybook-static/ -type f -exec md5sum {} \; | md5sum > storybook-hash-current.txt
         cat storybook-hash-current.txt
         echo "::set-output name=previous_hash::$(cat storybook-hash-previous.txt)"
         echo "::set-output name=current_hash::$(cat storybook-hash-current.txt)"
      shell: bash
    - name: Archive current Storybook build hash
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.artifactName}}
        path: storybook-hash-current.txt
    - name: Print info
      run: |
        echo "Previous hash: ${{ steps.storybook-hash.outputs.previous_hash}}"
        echo "Current hash: ${{steps.storybook-hash.outputs.current_hash }}"
        echo "Should deploy: ${{ steps.storybook-hash.outputs.previous_hash != steps.storybook-hash.outputs.current_hash }}"
        echo "Artifact found: ${{steps.previous_artifact.outputs.files_exists}}"
      shell: bash
    - run: echo "::set-output name=shouldDeploy::${{ steps.storybook-hash.outputs.previous_hash != steps.storybook-hash.outputs.current_hash }}"
      id: chromatic-checker
      shell: bash
